[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
cbor_metadata = true
optimizer = true
optimizer_runs = 5000

[etherscan]
#                   Paste TENDERLY_ACCESS_TOKEN            Chain ID         Verifier URL: RPC_URL/verify/etherscan
unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 1337337, url = "${ETH_RPC_URL}/verify/etherscan" }
